# melpazoid <https://github.com/riscy/melpazoid> build checks.

# If your package is on GitHub, enable melpazoid's checks by copying this file
# to .github/workflows/melpazoid.yml and modifying RECIPE and EXIST_OK below.
---
name: melpazoid
'on': [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get repo to access in conteiner
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: Install
        run: |
          python -m pip install --upgrade pip
          sudo apt-get install emacs-nox  && emacs --version
          git clone https://github.com/riscy/melpazoid.git ~/melpazoid
          pip install ~/melpazoid
      - name: Run
        env:
          LOCAL_REPO: ${{ github.workspace }}
          # RECIPE is your recipe as written for MELPA:
          RECIPE: (unmodified-buffer1 :fetcher github :repo "Anoncheg1/emacs-unmodified-buffer1")
          # set this to false (or remove it) if the package isn't on MELPA:
          # EXIST_OK: true
        run: |
          echo $GITHUB_REF
          if make -C ~/melpazoid |& tee output.log; then
            if grep -v 'Warning: argument `_' output.log | grep -q "Warning"; then
              echo "Warnings detected, failing workflow"
              exit 1
            fi
          else
            echo "Make command failed, failing workflow"
            exit 1
          fi
